# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-anvil-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.6
  - OpenZeppelin/openzeppelin-contracts@4.9.3
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version:
    remappings:
      - "github.com/yearn/yearn-vaults/blob/v0.4.6=yearn/yearn-vaults@0.4.6"
      - "@openzeppelin/contracts@4.9.3=OpenZeppelin/openzeppelin-contracts@4.9.3/contracts"
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.9.3/contracts"

reports:
  exclude_contracts:
    - Math
    - Vault
    - Ownable
    - Address
    - BaseStrategy
    - SafeERC20
    - StrategyProxy
